# Full working version
name: Auto Deploy to GitHub Pages

on:
  push:
    branches: [dev]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Checkout main branch in separate folder
        uses: actions/checkout@v4
        with:
          ref: main
          path: main

      - name: Copy build to main
        run: |
          rm -rf main/*
          cp -r build/* main/
          cp main/CNAME main/ || true

      - name: Commit and push to main
        run: |
          cd main
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-deploy from dev 🚀" || echo "No changes to commit"
          git push origin main --force
