name: Auto Deploy to GitHub Pages

on:
  push:
    branches: [dev]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: List dist folder contents (debug)
        run: ls -alh dist/

      - name: Checkout main branch in separate folder
        uses: actions/checkout@v4
        with:
          ref: main
          path: main

      - name: Preserve CNAME file
        run: cp main/CNAME ../CNAME_backup || true

      - name: Clean main folder
        run: rm -rf main/*

      - name: Copy build files
        run: cp -r dist/* main/

      - name: Restore CNAME file
        run: cp ../CNAME_backup main/CNAME || true

      - name: Commit and push to main
        run: |
          cd main
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-deploy from dev 🚀" || echo "No changes to commit"
          git push origin main --force
